# Generated by Django 4.2.13 on 2024-06-26 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "valid_from",
                    models.DateTimeField(
                        db_comment="사용자가 구매 시 쿠폰을 적용하기 위해 입력해야 하는 코드"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        db_comment="쿠폰 유효 기간의 시작 시점을 나태내는 날짜/시간 값"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        db_comment="할인율을 나타내는 정수 값",
                        help_text="Percentage value (0 to 100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_comment="쿠폰이 활성 상태인지를 나타내는 값"),
                ),
            ],
        ),
    ]
